-- ========================
-- SCHEMA DLA PROJEKTU
-- ========================

create table users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255) not null,
    role     varchar(255) not null
        constraint chk_users_role
            check ((role)::text = ANY
                   (ARRAY ['ADMINISTRATOR','PRACOWNIK','KLIENT'])),
    username varchar(255) not null
        constraint uq_users_username
            unique,
    email    varchar(255) not null
);

alter table users owner to postgres;

create table clients
(
    id      bigint generated by default as identity
        primary key,
    email   varchar(255),
    name    varchar(255),
    user_id bigint
        constraint fk_clients_user
            references users
);

alter table clients owner to postgres;

create table orders
(
    id           bigint generated by default as identity
        primary key,
    client_email varchar(255),
    client_name  varchar(255),
    client_id    bigint
        constraint fk_orders_client
            references clients,
    order_date   date,
    deleted_at   timestamptz,
    deleted      boolean default false not null,
    notes        varchar(255),
    status       varchar(255) not null
);

alter table orders owner to postgres;

create table products
(
    id          bigserial primary key,
    name        varchar(255)     not null,
    description varchar(2000),
    price       numeric(10,2)    not null,
    quantity    integer          not null check (quantity >= 0),
    image_url   varchar(255)
);

alter table products owner to postgres;

create table order_items
(
    id           bigint generated by default as identity
        primary key,
    price        numeric(10,2) not null,
    product_name varchar(255),
    quantity     integer       not null check (quantity > 0),
    order_id     bigint not null
        constraint fk_order_items_order
            references orders on delete cascade,
    product_id   bigint not null
        constraint fk_order_items_product
            references products
);

alter table order_items owner to postgres;

-- ========================
-- Włączenie rozszerzenia pgcrypto (funkcje kryptograficzne)
-- ========================
CREATE EXTENSION IF NOT EXISTS pgcrypto;
